[package]
name = "resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
logger = {  path = "../logger" }
semconv = { path = "../semconv" }
schema = { path = "../schema" }
version = { path = "../version" }

regex.workspace = true
thiserror.workspace = true

url = "2.4.1"

