file_name: snake_case
function_name: snake_case
arg_name: snake_case
struct_name: PascalCase
field_name: snake_case

type_mapping:
  int: i64
  double: f64
  boolean: bool
  string: String
  "int[]": "[i64]"
  "double[]": "[f64]"
  "boolean[]": "[bool]"
  "string[]": "[String]"