[package]
name = "schema"
version = "0.1.0"
edition = "2021"

[dependencies]
semconv = { path = "../semconv" }
version = { path = "../version" }

serde.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
ureq.workspace = true
