[package]
name = "semconv"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
ureq.workspace = true
validator = { version = "0.16.1", features = ["derive"] }
